kind: Service
apiVersion: v1
metadata:
  name: realiticsai-lgu-manager-service
  labels:
    app: realiticsai-lgu-manager
spec:
  type: LoadBalancer
  selector:
    app: realiticsai-lgu-manager
  ports:
    -
      port: 80
      targetPort: 8080
      name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: realiticsai-lgu-manager-deployment
  labels:
    app: realiticsai-lgu-manager
spec:
  selector:
    matchLabels:
      app: realiticsai-lgu-manager
  replicas: 1
  template:
    metadata:
      labels:
        app: realiticsai-lgu-manager
        version: v1
    spec:
      containers:
        -
          name: realiticsai-lgu-manager
          image: 'eu-frankfurt-1.ocir.io/oraseemeaceeociworkshop/ivandelic/realiticsai/realiticsai-lgu-manager:latest'
          imagePullPolicy: Always
          ports:
            -
              containerPort: 8080
          env:
            - name: JAVAX_SQL_DATASOURCE_LGU_dash_MANAGER_dash_ORCL_dash_DS_DATASOURCE_USER
              valueFrom:
                secretKeyRef:
                  name: dbsecret
                  key: username
            - name: JAVAX_SQL_DATASOURCE_LGU_dash_MANAGER_dash_ORCL_dash_DS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbsecret
                  key: password
      imagePullSecrets:
        -
          name: ocirsecret